# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  App\Obsidian\Markdown\SymfonyRouterObsidianLinkUrlGenerator:
    arguments:
      - '@router'
      - 'app.content'

  App\Obsidian\Markdown\ObsidianLinkUrlGenerator:
    alias: 'App\Obsidian\Markdown\SymfonyRouterObsidianLinkUrlGenerator'

  App\Obsidian\Markdown\ObsidianMarkdown:
    arguments:
      - '@App\Obsidian\Markdown\ObsidianLinkUrlGenerator'

  cebe\markdown\Parser:
    alias: 'App\Obsidian\Markdown\ObsidianMarkdown'

  app.markdown_parser:
    alias: 'cebe\markdown\Parser'

  App\Controller\ContentController:
    arguments:
      - '%env(CONTENT_DIR)%'
      - '%env(CONTENT_INDEX)%'
      - '@app.markdown_parser'
      - '@router'
      - '@twig'
      - - '/.obsidian'
        - '/commit'
    autoconfigure: true
    public: true
