# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.content.route_name: 'app.content'
  app.content.base_path: '%env(CONTENT_DIR)%'
  app.content.index_path: '%env(CONTENT_INDEX)%'
  app.content.markdown_extensions: ['md']

services:
  App\File\FileUtil:
    factory: ['App\File\FileUtil', 'createFromSettings']
    arguments:
      - '%app.content.base_path%'
      - - '/.obsidian'
        - '/commit'
      - '%app.content.markdown_extensions%'


  App\Routing\SymfonyRouterUrlGenerator:
    arguments:
      - '@router'
      - '%app.content.route_name%'

  App\Routing\UrlGenerator:
    alias: 'App\Routing\SymfonyRouterUrlGenerator'

  App\Markdown\ObsidianMarkdown:
    arguments:
      - '@App\Routing\UrlGenerator'

  cebe\markdown\Parser:
    alias: 'App\Markdown\ObsidianMarkdown'

  app.markdown_parser:
    alias: 'cebe\markdown\Parser'

  App\Controller\Content\Controller:
    arguments:
      - '@App\File\FileUtil'
      - '@App\Routing\UrlGenerator'
      - '@app.markdown_parser'
      - '@twig'
      - '%app.content.index_path%'
      - '%app.content.markdown_extensions%'
    autoconfigure: true
    public: true
